[application]

[bundle]
identifier = "com.softberries"
publisher = "Softberries"

[web.app]

# HTML title tag content
title = "dios3"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
